### PR TITLE
Add authorization

### PR DESCRIPTION
**Pull request by nreal**
# Background
Add Authorization for CurrencyController endpoint

# Changes done
- Update Package references
- Add public key of Doppler to test and prod
- Add Integration tests

Can you review it?

### CODE REVIEW

**Comment by andresmoschini** [comment]
Looks great! does it work? did you try it? let me know if you need to get a valid token.

**Comment by nreal** [comment]
@andresmoschini Working with https://github.com/MakingSense/Doppler/blob/4168c16da7f379ae15151a7aede187fed3192697/Doppler.AutomationProcess/App.IntegrationQA.config#L62 for 
and this for Prod
https://github.com/MakingSense/Doppler/blob/4168c16da7f379ae15151a7aede187fed3192697/Doppler.AutomationProcess/App.Production.config#L62

**Comment by nreal** [comment]
@andresmoschini I do not sure if I have to add a unit test with  these token, because I expose this token in this repository

**Comment by andresmoschini** [comment]
> @andresmoschini I do not sure if I have to add a unit test with these token, because I expose this token in this repository

No, you can only include expired tokens in the repository. We have a couple of them in the _cuit service_, probably you are already using one of the in your tests.

**Pull request merged**
